using Haiku.Domain.Enums;

namespace Haiku.Domain.ValueObjects;

// Used by PoemEngine to validate syllable patterns during poem creation and editing.
// Each PoemType maps to one definition registered in the poem type registry.

/// <summary>
/// Defines the structural characteristics of a poem type, including its syllable pattern
/// and line constraints.
/// </summary>
/// <remarks>
/// <para>Each <see cref="PoemType"/> has a corresponding <c>PoemDefinition</c> that
/// encodes its structural rules. The definition record is used during poem validation
/// to verify that submitted text matches the expected syllable pattern. Definitions
/// are immutable value objects — once created for a given type, the pattern does not
/// change.</para>
/// <para>This record implements value equality semantics (auto-generated by the
/// <c>record</c> keyword), so two definitions with the same properties are
/// considered equal.</para>
/// </remarks>
public record PoemDefinition
{
    /// <summary>
    /// Gets the poetic form identifier.
    /// </summary>
    /// <value>A value from <see cref="PoemType"/> indicating the form.</value>
    public PoemType Type { get; init; }

    /// <summary>
    /// Gets the display name of the poem type.
    /// </summary>
    /// <value>A human-readable name for this form.</value>
    public string Name { get; init; } = string.Empty;

    /// <summary>
    /// Gets a description of the poem type's structural rules.
    /// </summary>
    /// <value>Explains the syllable pattern, rhyme scheme, or other constraints.</value>
    public string Description { get; init; } = string.Empty;

    /// <summary>
    /// Gets the required syllable counts per line, ordered by line position.
    /// </summary>
    /// <value>An array where each element represents the syllable count for the corresponding line.</value>
    public int[] SyllablePattern { get; init; } = [];
}
